repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: no-commit-to-branch
        name: Don't commit to main branch
      - id: check-case-conflict
        name: Check for case conflicts
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-symlinks
        name: Check for broken symlinks
      - id: check-json
        name: Check for valid JSON
      - id: check-yaml
        name: Check for valid YAML
      - id: detect-private-key
        name: Check for private keys
      - id: trailing-whitespace
        name: Fix trailing whitespaces
      - id: end-of-file-fixer
        name: Fix missing end-of-file line returns
        exclude: _config.yml|repository.yaml|tests/test-data/
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.2
    hooks:
      - id: reorder-python-imports
        name: Reorder python imports
  - repo: https://github.com/python/black
    rev: 22.6.0
    hooks:
      - id: black
        name: Run Black
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        name: Run Bandit
        args: [-ll, -s, B301]
        language_version: python3
